### ISSUE TITLE
Figures not well readable in Dark Mode

### ISSUE THREAD

**Issue by obruendl** [open-logic/open-logic#29]
reported by @tasgomes 

Figures are not readable on browsers with dark-mode because they have transparent background (which makes black lines invisible due to the dark-mode)

**Comment by obruendl** [comment]
@tasgomes

Please review if it now is fixed. I added white background and borders on the branch [feature/doc-fixes](https://github.com/open-logic/open-logic/tree/feature/doc-fixes).

If it is fixed, close the issue or confirm here.

**Comment by tasgomes** [comment]
@obruendl Seems good to me now. I don't have permissions to close the issue.
