### ISSUE TITLE
Wave images creator

### ISSUE THREAD

**Issue by ecstrema** [open-logic/open-logic#94]
The waveform images you have in the repo are super pretty. Example:

![image](https://github.com/user-attachments/assets/2528315f-21e8-47ae-a77b-2493686824d2)

How do you make them?

**Comment by rbrglez** [comment]
the tool's name is wavedrom

Check out this page: https://wavedrom.com/

**Comment by rbrglez** [comment]
also check out this list of interesting tools:

https://gist.github.com/blackcater/1701e845a963216541591106c1bb9d3b

**Comment by obruendl** [comment]
@rbrglez 

Cool - the first issue that was answered by somebody from the community :-)

Thanks for that.

@ecstrema As the question ins answered, I will proceed to close the issue.
